/*

    Problem Link: https://cses.fi/problemset/task/1110
    Name: Minimal Rotation
    Topic: String Algorithms

    A rotation of a string can be generated by moving characters one after another from beginning to end. For example, the rotations of acab are acab, caba, abac, and baca.

    Your task is to determine the lexicographically minimal rotation of a string.

    Input

    The only input line contains a string of length n. Each character is one of a–z.

    Output

    Print the lexicographically minimal rotation.

    Constraints
    1≤n≤106
    Example

    Input:
    acab

    Output:
    abac

*/

/*

    APPROACH 1:
        Concat the string to itself, generate all possible substrings and sort them

*/

